name: Build App and Deploy on Firebase
on: push

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: main
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: [14.x]
          cache: 'npm'
      - name: Install CI
        run: npm ci
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: YOUR_FIREBASE_TOKEN_HERE


